"""Provider protocol."""

from collections.abc import Sequence
from typing import Any, Protocol

from src.llm.models import LocalModel, ProviderMessage, ProviderOutput


class LLMProvider(Protocol):
    name: str
    model: str

    def health_check(self) -> bool: ...
    def list_local_models(self) -> tuple[LocalModel, ...]: ...
    def generate(self, messages: Sequence[ProviderMessage]) -> ProviderOutput: ...
    def generate_with_tools(
        self, messages: Sequence[ProviderMessage], tools: Sequence[dict[str, Any]]
    ) -> ProviderOutput: ...
    def count_or_estimate_tokens(self, text: str) -> int: ...
    def cancel(self) -> None: ...
    def close(self) -> None: ...
