"""Controller enumerations and reason codes."""

from enum import StrEnum


class ControllerMode(StrEnum):
    NATIVE = "NATIVE"
    OCCUPIED_NORMAL = "OCCUPIED_NORMAL"
    OCCUPIED_RECOVERY = "OCCUPIED_RECOVERY"
    VACANCY_GRACE = "VACANCY_GRACE"
    UNOCCUPIED_RELAXED = "UNOCCUPIED_RELAXED"
    HOLD = "HOLD"
    FAILSAFE_RESET = "FAILSAFE_RESET"
    DISABLED = "DISABLED"


class DecisionReason(StrEnum):
    NO_ACTION = "NO_ACTION"
    HOLD_CURRENT_COMMAND = "HOLD_CURRENT_COMMAND"
    APPLY_OCCUPIED_NORMAL = "APPLY_OCCUPIED_NORMAL"
    APPLY_OCCUPIED_RECOVERY = "APPLY_OCCUPIED_RECOVERY"
    APPLY_UNOCCUPIED_RELAXATION = "APPLY_UNOCCUPIED_RELAXATION"
    RESET_TO_NATIVE_CONTROL = "RESET_TO_NATIVE_CONTROL"
    REJECT_MISSING_DATA = "REJECT_MISSING_DATA"
    REJECT_STALE_STATE = "REJECT_STALE_STATE"
    REJECT_INVALID_SEQUENCE = "REJECT_INVALID_SEQUENCE"
    REJECT_PLENUM = "REJECT_PLENUM"
    REJECT_UNAPPROVED_ZONE = "REJECT_UNAPPROVED_ZONE"
    REJECT_OUT_OF_BOUNDS = "REJECT_OUT_OF_BOUNDS"
    TEMPERATURE_PROTECTION = "TEMPERATURE_PROTECTION"
    VACANCY_GRACE = "VACANCY_GRACE"
    DISABLED = "DISABLED"


class ActionType(StrEnum):
    NO_ACTION = "NO_ACTION"
    APPLY_SETPOINT = "APPLY_SETPOINT"
    RESET = "RESET"
    REJECT = "REJECT"
